const citas = [
    'Vayan a un arcade',
    'Vayan a los go karts',
    'Vayan a acampar o simplemente acampen en el patio',
    'Tomen alguna clase de baile juntos',
    'Vayan a los bolos',
    'Pinten retratos divertidos de ustedes mismos',
    'Tengan una guerra con pistolas de agua o bombuchas',
    'Cocinen juntos un platillo y después cómanlo',
    'Vayan a un partido de algún deporte',
    'Den un lindo paseo en bicicleta',
    'Pueden ir a un café y jugar un juego de mesa',
    'Vayan a un balneario',
    'Prueben  ir a un escape room juntos y prueben sus habilidades de escape',
    'Jueguen algún deporte nuevo para los dos',
    'Hagan una velada sin luz',
    'Hagan una fiesta sin motivo e inviten a sus amigos',
    'Vayan a cenar y prueben cosas que nunca han comido',
    'Vayan a un bazar juntos y exploren todos los artículos y vean si encuentran algo interesante',
    'Caminen por la ciudad y busquen lugares interesantes a los que nunca habían entrado',
    'Armen un rompecabezas juntos',
    'Prueben un nuevo postre juntos',
    'Hagan una cápsula del tiempo juntos',
    'Tengan una cita en algún juego online',
    'Graben y editen un video juntos',
    'Hagan una sesión fotográfica divertida',
    'Vayan a luna librería y compren un libro para que el otro lo lea',
    'Vayan al planetario juntos o algún lugar interesante',
    'Vayan a un museo',
    'Vayan a un evento de comedia stand-up',
    'Busque si hay un lugar en su ciudad donde puedan ir a remar y platicar',
    'Hagan un picnic juntos',
    'Vayan a un obra de teatro local',
    'Vayan a un festival o concierto local',
    'Vayan a un mirador y vean una puesta de sol juntos',
    'Vayan a un café y háganse preguntas divertidas para conocerse más',
    'Vayan juntos al zoológico',
    'Vayan a un parque local y jueguen en los juegos como cuando eran niños',
    'Vayan a una galería local',
    'Vayan a una feria local',
    'Aprendan a hacer origami juntos',
    'Vean una película en casa',
    'Comiencen una serie juntos',
    'Hagan una lista de cosas por hacer antes de morir y luego compartan sus ideas',
    'Aprendan juntos un nuevo juego de mesa',
    'Una simple caminata por la ciudad y comprar un helado',
    'Vean sus videos musicales favoritos juntos',
    'Vayan un club de libros o de idiomas juntos',
    'Vayan a un circo juntos',
    'Hagan un pequeño viaje juntos aunque sea de un día',
    'Aprendan un nuevo idioma juntos',
    'Compren y lean unos comics',
    'Vuelen un barrilete en un día bonito',
    'Tomen un masaje juntos',
    'Vean sus películas favoritas de la infancia',
    'Creen su propio día festivo de pareja y celebren cada año',
    'Vayan a un lugar donde puedan ver las estrellas juntos',
    'Hagan una fiesta con temática de otro país',
    'Hagan un postre juntos',
    'Elijan una serie de películas y hagan un maratón',
    'Jueguen laser tag juntos',
    'Vean fotos de su infancia',
    'Vean videos de misterio juntos',
    'Vayan de compras juntos',
    'Tomen un día para desayunar juntos',
    'Vayan a un feria y suban a los juegos',
    'Vayan a un espectáculo de mañana o tarde',
    'Paseen a sus mascotas por el parque',
    'Vayan a un autocinema o vean una película en el auto en un lugar bonito',
    'Vayan al karaoke',
    'Hagan caridad juntos',
    'Lean el mismo libro y luego coméntenlo',
    'Vayan a un festival de cine',
    'Vayan a algún lugar a observar a la gente y creen historias divertidas sobre ellos',
    'Construyan un fuerte',
    'Visiten un jardín botánico',
    'Vayan a la playa juntos',
    'Creen un playlist juntos',
    'Jueguen "yo nunca nunca"',
    'Planeen una cena temática con sus amigos',
    'Tomen muchos test de personalidad juntos',
    'Vean una película de terror juntos',
    'anejen por la ciudad desde el atardecer hasta la noche',
    'Hagan una caminata por la naturaleza',
    'Compren libros para colorear y hagan eso mientras platican de cualquier cosa',
    'Tomen una clase de pintura juntos',
    'Hagan "brunch" juntos',
    'Vayan a una tienda de discos y descubran nueva música',
    'Vayan a una cata de vino, café o queso cerca de ustedes',
    'Ahorren y hagan un vuelo en globo aerostático',
    'Vayan a una cita doble',
    'Hagan rappel o escalada en roca juntos',
    'Creen su propia pizza',
    'Vayan a una convención',
    'Quédense en casa y pasen una tarde normal juntos',
    'Pasen un día haciendo solamente cosas nuevas',
    'Jueguen verdad o castigo',
    'Jueguen videojuegos',
    'Hagan una búsqueda del tesoro por la ciudad',
    'Vayan al aeropuerto y compren un ticket al destino más barato',
];
const citaTexto = document.querySelector('.cita-texto');
const citaBoton = document.querySelector('.cita-boton');
const citaNumero = document.querySelector('.cita-numero');

let cantidad = citas.length;

function citaRandom() {
    let random = Math.floor(Math.random() * cantidad + 1);
    citaTexto.textContent = citas[random];
    citaNumero.textContent = random;
}

citaBoton.addEventListener('click', citaRandom);
